# Generated by Django 3.0.8 on 2020-07-26 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=200)),
                ('produtos_aceitos_para_logo', models.TextField()),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=200)),
                ('data_publicada', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Grafica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_grafica', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=200)),
                ('nome_servicos', models.TextField()),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=200)),
                ('data_publicada', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
